import type { ProductSurfaceAssignment, TierBoundaryCase } from './client.js';

export const REGISTERED_TOOL_NAMES = [
  'route_intent_wizard',
  'plan_stack_bootstrap',
  'wizard_new_site_lite',
  'wizard_stack_bootstrap',
  'wizard_relaunch_lite',
  'wizard_optimization_lite',
  'wizard_extension_lite',
  'run_free_wizard_preset',
  'run_free_guided_transition',
  'plan_rebuild_strategy',
  'critique_rebuild_strategy',
  'assess_site',
  'plan_brand_adaptation',
  'queue_change',
  'list_change_queue',
  'review_change',
  'apply_change',
  'plan_premium_library_usage',
  'import_premium_library_asset',
  'route_advanced_scenario',
  'advanced_creator_mode',
  'get_template_data',
  'update_template_data',
  'extract_sections',
  'suggest_pipeline_path',
  'extract_design_tokens',
  'get_destination_capabilities',
  'get_site_fingerprint',
  'get_global_styles',
  'set_global_colors',
  'set_global_typography',
  'list_templates',
  'get_template',
  'create_template',
  'update_template',
  'delete_template',
  'rename_template',
  'duplicate_template',
  'bulk_rename',
  'list_by_type',
  'set_category',
  'set_tags',
  'audit_library',
  'critique_elementor_output',
  'list_elementor_pages',
  'get_page_data',
  'save_page_section_as_template',
  'update_page_data',
  'compose_page_from_templates',
  'save_full_page_as_template',
  'set_site_context',
  'get_site_context',
  'get_recommendations',
  'get_advanced_recommendations',
  'plan_advanced_upgrade_path',
  'explain_recommendation',
  'get_site_info',
  'list_sites',
  'switch_site',
  'search_stock_images',
  'generate_ai_image',
  'list_premium_library_assets',
  'inspect_premium_library_asset',
  'sideload_stock_image',
  'validate_elementor_write',
  'set_site_logo',
  'wizard_brand_setup',
  'creator_mode',
  'wizard_theme_builder',
  'list_menus',
  'create_menu',
  'delete_menu',
  'list_menu_items',
  'create_menu_item',
  'update_menu_item',
  'delete_menu_item',
  'list_menu_locations',
  'assign_menu_location',
  'create_page',
  'create_post',
  'update_post_meta',
  'delete_post',
  'list_taxonomies',
  'create_term',
  'update_term',
  'delete_term',
  'list_post_types',
  'list_media',
  'get_media',
  'update_media',
  'delete_media',
  'audit_unused_media',
  'flush_elementor_cache',
  'get_performance_report',
  'get_seo_meta',
  'get_site_settings',
  'optimize_elementor_assets',
  'update_seo_meta',
  'update_site_settings',
] as const;

export type RegisteredToolName = (typeof REGISTERED_TOOL_NAMES)[number];

export const TOOL_TIER_ASSIGNMENTS: ProductSurfaceAssignment[] = [
  {
    id: 'route_intent_wizard',
    label: 'Intent wizard routing',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free needs a scenario-first front door that turns user intent into the next sensible guided path.',
  },
  {
    id: 'plan_stack_bootstrap',
    label: 'Stack bootstrap front door',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should act as a 360-degree starting point even when Elementor is not installed yet.',
    dependsOn: ['route_intent_wizard'],
  },
  {
    id: 'wizard_new_site_lite',
    label: 'New Site Lite wizard',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free needs a concrete new-site runtime wizard for idea-first and brand-first entry states.',
    dependsOn: ['route_intent_wizard', 'wizard_brand_setup', 'creator_mode'],
  },
  {
    id: 'wizard_stack_bootstrap',
    label: 'Stack bootstrap wizard',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free needs a concrete bootstrap runtime wizard that turns routing into phased baseline, foundation, and first-build actions.',
    dependsOn: ['plan_stack_bootstrap', 'wizard_brand_setup', 'creator_mode'],
  },
  {
    id: 'wizard_relaunch_lite',
    label: 'Relaunch Lite wizard',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should support preservation-aware relaunch lite work before deeper structural Advanced execution begins.',
    dependsOn: ['route_intent_wizard', 'get_recommendations', 'creator_mode'],
  },
  {
    id: 'wizard_optimization_lite',
    label: 'Optimization Lite wizard',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should translate optimization intent into a real low-risk guided loop instead of stopping at raw recommendations.',
    dependsOn: ['route_intent_wizard', 'get_recommendations', 'explain_recommendation'],
  },
  {
    id: 'wizard_extension_lite',
    label: 'Extension Lite wizard',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should support restrained, support-aware extension work without immediately pushing users into deeper Advanced rollout.',
    dependsOn: ['route_intent_wizard', 'get_recommendations', 'creator_mode'],
  },
  {
    id: 'run_free_wizard_preset',
    label: 'Free wizard preset runner',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should begin to support limited guided execution for safe presets without turning scenario-first flows into unsafe one-click automation.',
    dependsOn: ['wizard_stack_bootstrap', 'wizard_relaunch_lite', 'wizard_optimization_lite'],
    notes: ['Only presets marked safe_execute may run directly; preview_only remains part of the guidance layer.'],
  },
  {
    id: 'run_free_guided_transition',
    label: 'Free guided transition runner',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should support short scenario-aware guided transitions for its most important early paths before users are dropped into isolated tool calls.',
    dependsOn: ['run_free_wizard_preset', 'wizard_stack_bootstrap', 'wizard_optimization_lite'],
    notes: ['This chains safe and preview-only presets together without turning Free into unsafe full automation.'],
  },
  {
    id: 'assess_site',
    label: 'Site assessment',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Core Free intelligence lift and the basis for recommendations.',
  },
  {
    id: 'set_site_context',
    label: 'Set site context',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free onboarding context is part of the core guided setup.',
  },
  {
    id: 'get_site_context',
    label: 'Get site context',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free operators need visibility into stored onboarding context.',
  },
  {
    id: 'get_recommendations',
    label: 'Recommendation engine',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Prioritized recommendations are a headline Free promise.',
    dependsOn: ['assess_site', 'set_site_context'],
  },
  {
    id: 'explain_recommendation',
    label: 'Recommendation guide',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Guided next steps are part of the Free workflow surface.',
    dependsOn: ['get_recommendations'],
  },
  {
    id: 'get_advanced_recommendations',
    label: 'Advanced recommendation depth',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced needs a deeper additive recommendation layer for premium-library usage, critique, governance, and stronger workflow differentiation.',
    dependsOn: ['get_recommendations'],
  },
  {
    id: 'plan_advanced_upgrade_path',
    label: 'Advanced upgrade path planning',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced needs an honest scenario-aware upgrade and stack-shaping seam so Elementor Pro, Elementify Advanced, and curated addon choices stay distinct.',
    dependsOn: ['get_advanced_recommendations', 'get_destination_capabilities'],
  },
  {
    id: 'get_site_fingerprint',
    label: 'Site fingerprint',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Destination understanding should remain mirror-safe and public.',
  },
  {
    id: 'get_destination_capabilities',
    label: 'Destination capabilities',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Capability transparency supports Free guidance and validation.',
    dependsOn: ['assess_site', 'get_site_fingerprint'],
  },
  {
    id: 'validate_elementor_write',
    label: 'Write validation',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Honest validation is part of the Free-safe execution layer.',
  },
  {
    id: 'get_site_info',
    label: 'Site info',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Basic operator visibility belongs in Free.',
  },
  {
    id: 'list_sites',
    label: 'List configured sites',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Agent-native setup in Free includes local multi-site config awareness.',
    notes: ['This is local operator convenience, not Studio cloud reuse.'],
  },
  {
    id: 'switch_site',
    label: 'Switch configured site',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free setup should not be artificially limited by local config switching.',
    notes: ['Local site switching is not equivalent to Studio cross-site orchestration.'],
  },
  {
    id: 'list_templates',
    label: 'List templates',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Local Elementor Library management is core Free functionality.',
  },
  {
    id: 'get_template',
    label: 'Get template',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Reading local templates is part of the Free local-library surface.',
  },
  {
    id: 'create_template',
    label: 'Create template',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free includes generating and assembling simple structures into the local library.',
  },
  {
    id: 'update_template',
    label: 'Update template metadata',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free must support practical local template management.',
  },
  {
    id: 'delete_template',
    label: 'Delete template',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should not be crippled for local library cleanup.',
    notes: ['Governance and scoped API keys remain the safety layer.'],
  },
  {
    id: 'rename_template',
    label: 'Rename template',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Naming and cleanup are essential parts of Free library hygiene.',
  },
  {
    id: 'duplicate_template',
    label: 'Duplicate template',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Basic local reuse belongs in Free.',
  },
  {
    id: 'bulk_rename',
    label: 'Bulk rename templates',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should support practical local-library organization, not just inspection.',
  },
  {
    id: 'plan_premium_library_usage',
    label: 'Premium library usage plan',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'This is the first provider-aware Advanced workflow for using curated premium assets without implying cloud-library behavior.',
  },
  {
    id: 'import_premium_library_asset',
    label: 'Premium library import',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced must be able to execute the curated premium-library flow through the dedicated local import seam, not just inspect and plan it.',
    dependsOn: ['inspect_premium_library_asset', 'plan_premium_library_usage'],
  },
  {
    id: 'route_advanced_scenario',
    label: 'Advanced scenario routing',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced needs a scenario-first private front door so deeper paid workflows present as operational routes instead of a flat extra tool shelf.',
    dependsOn: ['get_advanced_recommendations', 'advanced_creator_mode'],
  },
  {
    id: 'advanced_creator_mode',
    label: 'Advanced creator mode',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced needs a deeper orchestrated workflow mode that ties premium rollout, Theme Builder rollout, and critique loops together in one guided surface.',
    dependsOn: ['get_advanced_recommendations', 'import_premium_library_asset', 'wizard_theme_builder'],
  },
  {
    id: 'list_premium_library_assets',
    label: 'Premium library catalog',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced needs a curated asset catalog before planning or importing premium structures.',
  },
  {
    id: 'inspect_premium_library_asset',
    label: 'Premium library inspection',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Asset inspection is part of the private Advanced premium-library workflow and stays local-site operational.',
  },
  {
    id: 'get_template_data',
    label: 'Get raw template data',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Existing-block customization requires raw structure access in Free.',
  },
  {
    id: 'update_template_data',
    label: 'Update raw template data',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free includes intelligent customization of existing Elementor structures.',
  },
  {
    id: 'extract_sections',
    label: 'Extract sections',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Section extraction is part of the local customization and assembly loop.',
  },
  {
    id: 'list_by_type',
    label: 'List templates by type',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Template organization remains part of the Free local library story.',
  },
  {
    id: 'set_category',
    label: 'Set template category',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free guidance depends on usable local template metadata.',
  },
  {
    id: 'set_tags',
    label: 'Set template tags',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free creator-light flows benefit from local tag metadata.',
  },
  {
    id: 'audit_library',
    label: 'Audit template library',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Library audit is part of the Free intelligence and hygiene surface.',
  },
  {
    id: 'list_elementor_pages',
    label: 'List Elementor pages',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free includes simple page and section workflows on the current site.',
  },
  {
    id: 'get_page_data',
    label: 'Get page data',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Current-site inspection is part of Free page workflows.',
  },
  {
    id: 'save_page_section_as_template',
    label: 'Save page section as template',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free should support extracting reusable value from existing pages.',
  },
  {
    id: 'update_page_data',
    label: 'Update page data',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Simple assembly and customization on the current site are part of Free.',
  },
  {
    id: 'compose_page_from_templates',
    label: 'Compose page from templates',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Simple page assembly is explicitly part of the Free promise.',
  },
  {
    id: 'save_full_page_as_template',
    label: 'Save full page as template',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Free local reuse includes preserving current-site page structures as templates.',
  },
  {
    id: 'get_global_styles',
    label: 'Get global styles',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Brand-state understanding is part of the Free brand setup loop.',
  },
  {
    id: 'set_global_colors',
    label: 'Set global colors',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Brand setup is part of the Free intelligent lift.',
  },
  {
    id: 'set_global_typography',
    label: 'Set global typography',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Brand setup is part of the Free intelligent lift.',
  },
  {
    id: 'set_site_logo',
    label: 'Set site logo',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Logo setup is part of Free onboarding and brand lift.',
  },
  {
    id: 'wizard_brand_setup',
    label: 'Brand setup wizard',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'One of the strong Free wizard surfaces for guided onboarding.',
  },
  {
    id: 'creator_mode',
    label: 'Creator mode',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Creator Wizard Light belongs in Free as a core differentiation surface.',
    notes: ['Free surface is creator-light; deeper creator depth remains Advanced.'],
  },
  {
    id: 'wizard_theme_builder',
    label: 'Theme Builder wizard',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Theme Builder crosses from creator-light into site-wide structural workflows and should mark Advanced depth.',
  },
  {
    id: 'search_stock_images',
    label: 'Search stock images',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Media sourcing is useful workflow acceleration but not required for the Free core promise.',
  },
  {
    id: 'sideload_stock_image',
    label: 'Sideload stock image',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Operational media ingestion belongs in the deeper Advanced creation layer.',
  },
  {
    id: 'generate_ai_image',
    label: 'Generate AI image',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'AI media generation is additive creator power and should remain private to Advanced.',
  },
  {
    id: 'queue_change',
    label: 'Queue change',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Approval-oriented governance is part of stronger Advanced operational workflows.',
  },
  {
    id: 'list_change_queue',
    label: 'List change queue',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Queued review is part of Advanced operational discipline.',
  },
  {
    id: 'review_change',
    label: 'Review queued change',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Human-in-the-loop review flows belong in Advanced.',
  },
  {
    id: 'apply_change',
    label: 'Apply queued change',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Governed change application belongs in Advanced.',
  },
  {
    id: 'extract_design_tokens',
    label: 'Extract design tokens',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Token extraction is mainly valuable as input to deeper adaptation and planning flows.',
  },
  {
    id: 'plan_brand_adaptation',
    label: 'Brand adaptation plan',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Brand adaptation is a deeper workflow layer and a clear Advanced differentiator.',
    dependsOn: ['extract_design_tokens'],
  },
  {
    id: 'plan_rebuild_strategy',
    label: 'Rebuild strategy planning',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Typed planning and stronger agent-native workflow behavior belong in Advanced.',
  },
  {
    id: 'critique_rebuild_strategy',
    label: 'Rebuild strategy critique',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Strategy critique is part of the deeper Advanced operator layer.',
    dependsOn: ['plan_rebuild_strategy'],
  },
  {
    id: 'critique_elementor_output',
    label: 'Elementor output critique',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Output critique and repair guidance are deeper productivity features beyond Free validation.',
    dependsOn: ['validate_elementor_write'],
  },
  {
    id: 'suggest_pipeline_path',
    label: 'Pipeline path suggestion',
    tier: 'studio_future',
    visibility: 'future',
    kind: 'tool',
    rationale: 'Conversational control and orchestration belong to the future Studio operating mode, even if a seed exists today.',
    notes: ['Keep as an internal seam until a Studio-facing orchestration story is ready.'],
  },
  {
    id: 'list_menus',
    label: 'List navigation menus',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Menu reading is part of Free theme-structure awareness.',
  },
  {
    id: 'create_menu',
    label: 'Create navigation menu',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Menu creation is part of Free theme-structure management.',
  },
  {
    id: 'delete_menu',
    label: 'Delete navigation menu',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Menu deletion is part of Free theme-structure management (consistent with delete_template precedent).',
  },
  {
    id: 'list_menu_items',
    label: 'List menu items',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Reading menu items is part of Free theme-structure awareness.',
  },
  {
    id: 'create_menu_item',
    label: 'Create menu item',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Creating menu items is part of Free theme-structure management.',
  },
  {
    id: 'update_menu_item',
    label: 'Update menu item',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Updating menu items is part of Free theme-structure management.',
  },
  {
    id: 'delete_menu_item',
    label: 'Delete menu item',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Deleting menu items is part of Free theme-structure management.',
  },
  {
    id: 'list_menu_locations',
    label: 'List menu locations',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Reading theme menu locations is part of Free theme-structure awareness.',
  },
  {
    id: 'assign_menu_location',
    label: 'Assign menu to location',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Assigning menus to theme locations is part of Free theme-structure management.',
  },
  {
    id: 'create_page',
    label: 'Create page',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Creating WordPress pages is part of Free content management.',
  },
  {
    id: 'create_post',
    label: 'Create post',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Creating WordPress posts is part of Free content management.',
  },
  {
    id: 'update_post_meta',
    label: 'Update post meta',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Updating post metadata (slug, excerpt, featured image) is part of Free content management.',
  },
  {
    id: 'delete_post',
    label: 'Delete post',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Deleting posts is part of Free content management (governance and scoped API keys provide safety).',
  },
  {
    id: 'list_taxonomies',
    label: 'List taxonomies',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Listing taxonomies is part of Free content structure awareness.',
  },
  {
    id: 'create_term',
    label: 'Create term',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Creating taxonomy terms is part of Free content structure management.',
  },
  {
    id: 'update_term',
    label: 'Update term',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Updating taxonomy terms is part of Free content structure management.',
  },
  {
    id: 'delete_term',
    label: 'Delete term',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Deleting taxonomy terms is part of Free content structure management.',
  },
  {
    id: 'list_post_types',
    label: 'List post types',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Listing post types is part of Free content structure awareness.',
  },
  {
    id: 'list_media',
    label: 'List media',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Listing media attachments is part of Free content management.',
  },
  {
    id: 'get_media',
    label: 'Get media details',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Getting media details (including image sizes) is part of Free content management.',
  },
  {
    id: 'update_media',
    label: 'Update media metadata',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Updating alt text, title, caption, and description is part of Free content management.',
  },
  {
    id: 'delete_media',
    label: 'Delete media',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Deleting media attachments (move to trash or permanently delete) is part of Free content management.',
  },
  {
    id: 'audit_unused_media',
    label: 'Unused media audit',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Advanced media workflows include heuristic analysis of unused attachments for library cleanup.',
  },
  {
    id: 'flush_elementor_cache',
    label: 'Flush Elementor cache',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Cache flushing is a basic maintenance operation for Elementor sites and should be part of Free.',
  },
  {
    id: 'get_performance_report',
    label: 'Get performance report',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Performance reporting helps users understand site optimization status and is part of Free intelligence.',
  },
  {
    id: 'get_seo_meta',
    label: 'Get SEO meta',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Reading SEO metadata is part of Free content management and SEO optimization workflows.',
  },
  {
    id: 'get_site_settings',
    label: 'Get site settings',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Reading WordPress core settings is part of Free site intelligence and configuration awareness.',
  },
  {
    id: 'optimize_elementor_assets',
    label: 'Optimize Elementor assets',
    tier: 'advanced',
    visibility: 'private',
    kind: 'tool',
    rationale: 'Asset optimization is a deeper performance workflow that belongs in Advanced tier.',
  },
  {
    id: 'update_seo_meta',
    label: 'Update SEO meta',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Writing SEO metadata is part of Free content management and SEO optimization workflows.',
  },
  {
    id: 'update_site_settings',
    label: 'Update site settings',
    tier: 'free',
    visibility: 'public',
    kind: 'tool',
    rationale: 'Writing WordPress core settings is part of Free site configuration management.',
  },
];

export const TIER_BOUNDARY_CASES: TierBoundaryCase[] = [
  {
    id: 'theme-builder-boundary',
    decision: 'Keep wizard_theme_builder in Advanced.',
    rationale: 'Theme Builder changes site-wide structural delivery and should mark the step up from creator-light to deeper workflow control.',
    affectedSurfaces: ['wizard_theme_builder', 'plan_rebuild_strategy'],
  },
  {
    id: 'local-multi-site-vs-studio',
    decision: 'Keep list_sites and switch_site in Free.',
    rationale: 'Local operator switching is not the same as Studio cloud reuse or cross-site delivery orchestration.',
    affectedSurfaces: ['list_sites', 'switch_site', 'suggest_pipeline_path'],
  },
  {
    id: 'delete-template-in-free',
    decision: 'Keep delete_template in Free.',
    rationale: 'Free should feel operationally real; governance and scoped API keys are the safety mechanism rather than artificial crippleware.',
    affectedSurfaces: ['delete_template', 'queue_change'],
  },
  {
    id: 'control-plane-seed',
    decision: 'Treat suggest_pipeline_path as studio_future even though the seed exists in code.',
    rationale: 'It is strategically closer to future orchestration than to the current public Free or private Advanced promise.',
    affectedSurfaces: ['suggest_pipeline_path'],
  },
  {
    id: 'bootstrap-front-door',
    decision: 'Keep route_intent_wizard and plan_stack_bootstrap in Free.',
    rationale: 'The scenario-first front door is part of the public Free promise and should help users before deeper Advanced workflow logic begins.',
    affectedSurfaces: ['route_intent_wizard', 'plan_stack_bootstrap', 'get_advanced_recommendations'],
  },
  {
    id: 'free-runtime-wizard-families',
    decision: 'Keep new-site lite, stack bootstrap, extension lite, relaunch lite, and optimization lite runtime wizards in Free.',
    rationale: 'These flows are the concrete scenario-family execution layer behind the Free front door and should stay public before deeper Advanced orchestration begins.',
    affectedSurfaces: ['wizard_new_site_lite', 'wizard_stack_bootstrap', 'wizard_extension_lite', 'wizard_relaunch_lite', 'wizard_optimization_lite', 'advanced_creator_mode'],
  },
  {
    id: 'advanced-scenario-front-door',
    decision: 'Keep route_advanced_scenario in Advanced.',
    rationale: 'Advanced should expose a scenario-first private entry layer for deep relaunch, migration, premium rollout, and critique paths rather than only a deeper workflow tool shelf.',
    affectedSurfaces: ['route_advanced_scenario', 'advanced_creator_mode', 'get_advanced_recommendations'],
  },
];

const TOOL_TIER_MAP = new Map(
  TOOL_TIER_ASSIGNMENTS.map((assignment) => [assignment.id, assignment]),
);

export function getToolTierAssignment(toolName: string): ProductSurfaceAssignment | undefined {
  return TOOL_TIER_MAP.get(toolName);
}

export function findUnassignedToolNames(): string[] {
  return REGISTERED_TOOL_NAMES.filter((toolName) => !TOOL_TIER_MAP.has(toolName));
}
